version: "3.4"
volumes:
  my-db:
networks:
  app-network:
    driver: bridge
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - 3306:3306
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    networks:
      - app-network
    depends_on:
      - db
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app-network
